on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  go_version: '1.15.6'

jobs:
  build_docker:
    name: Build docker image (amd64)
    runs-on: ubuntu-latest
    environment: BuildRelease

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Apply patches
        env:
          GO_VERSION: ${{ env.go_version }}
        run: |
          envsubst '${GO_VERSION}' < Dockerfile > upstream/Dockerfile
          pushd upstream && git apply ../patches/*.patch && popd

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/heilerich/probridge

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: /upstream
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

